<?php

/**
 * @file
 * An installation file for WetKit Admin
 */

/**
 * Implements hook_install().
 */
function wetkit_admin_install() {

  // Update the administrator role to have all permissions.
  if ($administrator = user_role_load_by_name('administrator')) {
    $permissions = module_invoke_all('permission');
    unset($permissions['access wxt mobile']);
    user_role_grant_permissions($administrator->rid, array_keys($permissions));
  }
}
